fix: build not failed when quality gate is & data return in discord alter

diff --git a/.github/workflows/sonarcloud.yml b/.github/workflows/sonarcloud.yml
--- a/.github/workflows/sonarcloud.yml
+++ b/.github/workflows/sonarcloud.yml
@@ -65,11 +65,55 @@ jobs:
 
       - name: End SonarCloud analysis
         run: dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
+  
+  waitForQualityGate:
+    name: Wait for SonarCloud Quality Gate
+    runs-on: ubuntu-latest
+    needs: sonarcloud
+    steps:
+      - name: Check Quality Gate status
+        run: |
+          PROJECT_KEY="Ewillian_ByGameApi"
+          ORGANIZATION="ewillian"
+
+          # On récupère le chemin du rapport
+          TASK_URL=$(find . -name "report-task.txt" | head -n 1)
+          CE_TASK_ID=$(grep 'ceTaskId' $TASK_URL | cut -d'=' -f2)
+
+          echo "Waiting for SonarCloud analysis (taskId=$CE_TASK_ID)..."
+
+          STATUS="PENDING"
+          TIMEOUT=60
+          COUNT=0
+
+          while [[ "$STATUS" == "PENDING" && $COUNT -lt $TIMEOUT ]]; do
+            sleep 5
+            RESPONSE=$(curl -s -u "${{ secrets.SONAR_TOKEN }}:" "https://sonarcloud.io/api/ce/task?id=$CE_TASK_ID")
+            STATUS=$(echo "$RESPONSE" | jq -r '.task.status')
+            ((COUNT++))
+          done
+
+          if [ "$STATUS" != "SUCCESS" ]; then
+            echo "SonarCloud analysis failed or timed out."
+            exit 1
+          fi
+
+          ANALYSIS_ID=$(echo "$RESPONSE" | jq -r '.task.analysisId')
+
+          # Vérification de la quality gate
+          QG_STATUS=$(curl -s -u "${{ secrets.SONAR_TOKEN }}:" "https://sonarcloud.io/api/qualitygates/project_status?analysisId=$ANALYSIS_ID" | jq -r '.projectStatus.status')
+
+          echo "Quality Gate Status: $QG_STATUS"
+
+          if [ "$QG_STATUS" != "OK" ]; then
+            echo "❌ Quality Gate failed."
+            exit 1
+          fi
 
   fetchSonarSummary:
     name: Fetch SonarCloud Summary
     runs-on: ubuntu-latest
-    needs: sonarcloud
+    needs: [sonarcloud, waitForQualityGate]
 
     outputs:
       summary: ${{ steps.extract.outputs.summary }}
@@ -93,7 +137,13 @@ jobs:
           get_value() {
             jq -r --arg METRIC "$1" '
               if .component and .component.measures then
-                (.component.measures[]? | select(.metric==$METRIC) | .value) // "N/A"
+                (.component.measures[]? | select(.metric==$METRIC) |
+                  if has("periods") and (.periods | length > 0) then
+                    .periods[0].value
+                  else
+                    .value
+                  end
+                ) // "N/A"
               else
                 "N/A"
               end
@@ -116,7 +166,7 @@ jobs:
   notifyDiscord:
     name: Notify Discord
     runs-on: ubuntu-latest
-    needs: [sonarcloud, fetchSonarSummary]
+    needs: [sonarcloud, waitForQualityGate, fetchSonarSummary]
     if: always()
     steps:
       - name: Send Discord Notification
